version: '3'

services:
  db:
    container_name: db
    image: postgres:14-bullseye
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
